#include "test_src.h"

const char *test_fibo_src = "  .globl fibo\n"
                            "  .type fibo, @function\n"
                            "fibo:\n"
                            "  mov 0, %v1\n"
                            "  mov 1, %v2\n"
                            "\n"
                            "L0:\n"
                            "  skpn 0, %v0\n"
                            "  jmp L1\n"
                            "  mov %v2, %v3\n"
                            "  add %v1, %v2\n"
                            "  mov %v3, %v1\n"
                            "  add 0xFF, %v0\n"
                            "  jmp L0\n"
                            "\n"
                            "L1:\n"
                            "mov %v1, %v0\n"
                            "ret\n";

const char *test_my_add_src = "  .globl my_add\n"
                              "  .type my_add, @function\n"
                              "my_add:\n"
                              "  add %v1, %v0\n"
                              "ret\n";

const char *test_sum_rec_src = "  .globl sum_rec\n"
                               "  .type sum_rec, @function\n"
                               "sum_rec:\n"
                               "skpe 0, %v0\n"
                               "ret\n"
                               "mov %v0, %v4\n"
                               "add 1, %v0\n"
                               "call sum_rec\n"
                               "add %v4, %v0\n"
                               "ret\n";

const char *test_call_add_src = "_start:\n"
                                "mov 6, %v0\n"
                                "mov 8, %v1\n"
                                "call my_add\n"
                                "mov %v0, %vf\n";

const char *test_call_add_mem_src = "  .type _start, @function\n"
                                    "_start:\n"
                                    "  mov args, %i\n"
                                    "  movm %i, %v1\n"
                                    "  call my_add\n"
                                    "  mov %v0, %vf\n"
                                    "\n"
                                    "  .type args, @object\n"
                                    "args:\n"
                                    "  .byte 8\n"
                                    "  .byte 13\n";

const char *test_fact_table_src = "  .globl fact\n"
                                  "  .type fact, @function\n"
                                  "fact:\n"
                                  "  mov %v0, %v1\n"
                                  "  add 0x2, %v1\n"
                                  "  mov 0xf8, %v2\n"
                                  "  and %v2, %v1\n"
                                  "  skpn 0, %v1\n"
                                  "  jmp Ltable\n"
                                  "\n"
                                  "Lmax:\n"
                                  "  mov 0xff, %v0\n"
                                  "  jmp Lend\n"
                                  "\n"
                                  "Ltable:\n"
                                  "  mov table, %i\n"
                                  "  add %v0, %i\n"
                                  "  movm %i, %v0\n"
                                  "\n"
                                  "Lend:\n"
                                  "  ret\n"
                                  "\n"
                                  "  .type table, @object\n"
                                  "table:\n"
                                  "  .byte 0x1\n"
                                  "  .byte 0x1\n"
                                  "  .byte 0x2\n"
                                  "  .byte 0x3\n"
                                  "  .byte 0x6\n"
                                  "  .byte 0x18\n"
                                  "  .byte 0x78\n";
